linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - gochecknoglobals
    - godox
    - gofumpt
    - ireturn
    - lll
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl

# linters-settings:
#   tagliatelle:
#     case:
#       use-field-name: true
#       rules:
#         json: snake
