linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - gochecknoglobals
    - godox
    - gofumpt
    - gomnd
    - ireturn
    - lll
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
