name: lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  # https://github.com/golangci/golangci-lint-action
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup-go will automatically cache go.sum
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: go get .
      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
