name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # setup-go will automatically cache go.sum
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Run all tests
        run: go test ./...
